### PR TITLE
Fixed layout issues with the capture FAB in the demo

### PR DESCRIPTION
**Pull request by Alec-DeSouza**
### Pictures of the issue:
screenshot_20170314-213605 screenshot_20170314-213622
**(when using 3:2 and 16:9 aspect ratios on the Nexus 5)

### Pictures with the fix:
screenshot_20170314-214821 screenshot_20170314-214830
**(when using 3:2 and 16:9 aspect ratios on the Nexus 5)

### CODE REVIEW

**Comment by yaraki** [comment]
Can you reformat the code?

**Comment by Alec-DeSouza** [comment]
@yaraki Can you provide more details on what should be changed?

 (For example, should the Runnable inside repositionCaptureFab() be global?)

**Comment by yaraki** [comment]
On Android Studio,
Win/Linux: Ctrl + Alt + L
Mac: Option + Command + L

**Comment by Alec-DeSouza** [comment]
@yaraki Done.

Let me know if there's anything else that needs to be changed.

**Comment by yaraki** [comment]
Thank you!

**Pull request merged**
