### PR TITLE
Fix for front facing camera images being rotated incorrectly

### PR DESCRIPTION
**Pull request by mkotyk**
- Camera1 API: Split display orientation calculation from camera rotation calculation
- Adjusted camera rotation to flip when landscape
- Always apply parameters when opening a camera

Tested on Samsung S5 (SM_G900A), Moto G (XT1032), Samsung Galaxy Core LTE (SM-G386M)

### CODE REVIEW

**Comment by yaraki** [comment]
Can you sign the CLA?

**Comment by snowpong** [comment]
@mkotyk can you sign the CLA so @yaraki can merge it?

**Comment by mkotyk** [comment]
Hi guys,  the company I work for signed a CLA but I don't think the googlebot can handle it automatically.

**Comment by vuhung3990** [comment]
perfect, thank you @mkotyk

**Pull request merged**
