### PR TITLE
adjust image size to fit current view

### PR DESCRIPTION
**Pull request by alvarosct02**
When I use a fixed size for the CameraView like in the first picture, i realised the size of the saved photo differs from the displayed in the app

I came up with a fix to crop the image to only save the portion of the picture the user is really watching in the app. The comparison of the previous saved image and the cropped is show below.

image

image

### CODE REVIEW

**Comment by alvarosct02** [comment]
I just closed previous other pull request because I commit with another account.

**Comment by kevinpelgrims** [comment]
I personally prefer getting full sized pictures, based on the aspect ratio, even if the view does not fit. So I'm not sure if this should be the default behavior. Especially if there is no option to get the full size.

**Comment by kevinpelgrims** [comment]
You can get Bitmap dimensions without loading the entire Bitmap into memory. See instructions here: https://developer.android.com/training/displaying-bitmaps/load-bitmap.html#read-bitmap

**Comment by yaraki** [comment]
I agree with Kevin. The library should return a picture with the specified aspect ratio. I would like to enhance it so that it supports arbitrary aspect ratio.

**Pull request closed without merging**
